### ISSUE TITLE
 TypeError

### ISSUE THREAD

**Issue by theurere2** [franzholz/tslib_fetce#6]
I installed the following on TYPO3 12.4.23:
`"jambagecom/tt-board": "^1.16"`
`"jambagecom/div2007": "^2.2"`
`"jambagecom/tslib-fetce": "^0.9.1"`

Unfortunately I am getting the following error:
`
JambageCom\TslibFetce\EventListener\AfterCacheableContentIsGenerated::prefixLocalAnchorsWithScript(): 
Argument #1 ($tsfe) must be of type TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent given, called in /srv/app/vendor/jambagecom/tslib-fetce/Classes/EventListener/AfterCacheableContentIsGenerated.php on line 28
`

I attached an image of the error for more information.
![Screenshot 2024-12-20 at 15 13 08](https://github.com/user-attachments/assets/c1b334b5-84be-471b-9e50-544d99da6327)

**Comment by franzholz** [comment]
Test this patch!
